# Generated by Django 6.1 on 2026-08-14 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='accounts.organization'),
            preserve_default=False,
        ),
    ]
