services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: webhook_relay
      POSTGRES_PASSWORD: webhook_relay
      POSTGRES_DB: webhook_relay
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
